# Generated by Django 4.2.18 on 2025-01-25 17:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mcte.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='campeonatos/', validators=[mcte.models.validar_tamanho_imagem])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Carreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='treinadores/', validators=[mcte.models.validar_tamanho_imagem])),
                ('criado', models.BooleanField(default=False, verbose_name='Treinador foi criado manualmente?')),
                ('usuario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('apelido', models.CharField(default='', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='times/', validators=[mcte.models.validar_tamanho_imagem])),
                ('criado', models.BooleanField(default=False, verbose_name='Time foi criado manualmente?')),
                ('usuario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='2025/2026', max_length=50)),
                ('carreira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='mcte.carreira')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('posicao', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=50)),
                ('criado', models.BooleanField(default=False, verbose_name='Jogador foi criado manualmente?')),
                ('clube_atual', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade de Jogos')),
                ('gol', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade de Gols')),
                ('assistencia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade de Assistências')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='mcte.campeonato')),
                ('carreira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='mcte.carreira')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='mcte.jogador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='mcte.temporada')),
            ],
        ),
        migrations.AddField(
            model_name='carreira',
            name='time_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreiras', to='mcte.time'),
        ),
        migrations.AddField(
            model_name='carreira',
            name='treinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreiras', to='mcte.treinador'),
        ),
        migrations.AddField(
            model_name='carreira',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreiras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CarreiraTimeJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_atual', models.BooleanField(default=True)),
                ('carreira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreira_times_jogadores', to='mcte.carreira')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreira_times_jogadores', to='mcte.jogador')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreira_times_jogadores', to='mcte.time')),
            ],
            options={
                'verbose_name': 'Carreira-Time-Jogador',
                'verbose_name_plural': 'Carreira-Times-Jogadores',
                'unique_together': {('carreira', 'time', 'jogador')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='carreira',
            unique_together={('nome', 'usuario')},
        ),
    ]
