# Generated by Django 4.2.18 on 2025-01-28 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estatistica',
            old_name='assistencia',
            new_name='assistencias',
        ),
        migrations.RenameField(
            model_name='estatistica',
            old_name='gol',
            new_name='gols',
        ),
    ]
