# Generated by Django 4.0.8 on 2025-01-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='time_atual',
        ),
        migrations.AddField(
            model_name='carreiratimejogador',
            name='time_atual',
            field=models.BooleanField(default=True),
        ),
    ]
