# Generated by Django 4.2.18 on 2025-01-29 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcte', '0002_rename_assistencia_estatistica_assistencias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatistica',
            name='carreira',
        ),
        migrations.RemoveField(
            model_name='estatistica',
            name='jogador',
        ),
        migrations.AddField(
            model_name='estatistica',
            name='carreira_time_jogador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='mcte.carreiratimejogador'),
        ),
    ]
