# Generated by Django 4.2.18 on 2025-01-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcte', '0003_remove_estatistica_carreira_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarreiraCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreira_campeonatos', to='mcte.campeonato')),
                ('carreira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreira_campeonatos', to='mcte.carreira')),
            ],
        ),
    ]
