# Generated by Django 4.2.18 on 2025-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcte', '0004_carreiracampeonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreiratimejogador',
            name='titular',
            field=models.BooleanField(default=False),
        ),
    ]
